### ISSUE TITLE
Please Remove The Listed Domain

### ISSUE THREAD

**Issue by yoo-developer** [BuildBot42/discord-scam-links#112] opened 2023-05-06 14:25 UTC
-discordpanel.net

we submitted a pull request to delete this domain from the list as its not a scam , for more info's contact me  : 
CodIngLoop#5443
houssemchelihi.000@gmail.com

**Comment by BuildBot42** [comment] 2023-05-06 14:46
Duplicate of https://github.com/BuildBot42/discord-scam-links/pull/111, redirect all conversation there

**Closed by BuildBot42** 2023-05-06 14:46 UTC
